query: '
  query($owner:String!, $name:String!) {
    repository(owner:$owner, name:$name) {
      pinnedIssues(first:3) {
        nodes {
          issue {
            id
            number
            labels (first: 10) {
              nodes {
                name
              }
            }
          }
        }
      }
    }
  }'
variables:
  owner:
    type: arg
    name: owner
  name:
    type: arg
    name: name
