query: '
  query($owner:String!, $name:String!) {
    repository(owner:$owner, name:$name) {
      pinnedIssues(first:3) {
        nodes {
          issue {
            number
            labels (first: 10) {
              nodes {
                name
              }
            }
          }
        }
      }
    }
  }'
variables:
  number: '$jq{pinnedIssues.json;.data.repository.pinnedIssues.nodes[]|{number: .issue.number, label: .issue.labels.nodes[].name}|if .label=="duplicate" then .number else empty end}'
  name: $arg{name}
